# Generated by Django 3.1.2 on 2020-10-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_client',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_worker',
        ),
        migrations.AddField(
            model_name='user',
            name='expertise',
            field=models.ManyToManyField(to='users.Expertise'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ManyToManyField(to='users.Role'),
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
