# Generated by Django 3.1.2 on 2020-11-18 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0018_auto_20201118_0932'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
