# Generated by Django 3.1.2 on 2020-11-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='client',
            field=models.BooleanField(default=False, verbose_name='is_client'),
        ),
    ]
