# Generated by Django 3.1.2 on 2020-10-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201008_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expertise',
            field=models.ManyToManyField(related_name='show_workers', to='users.Expertise'),
        ),
    ]
