# Generated by Django 3.1.2 on 2020-10-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201009_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expertise',
            field=models.ManyToManyField(related_name='users', to='users.Expertise'),
        ),
    ]
