# Generated by Django 3.1.2 on 2020-11-18 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='client',
            new_name='is_client',
        ),
    ]
