# Generated by Django 3.1.2 on 2020-10-09 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201009_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expertise',
            old_name='field',
            new_name='name',
        ),
    ]
