# Generated by Django 3.1.2 on 2020-10-21 12:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('translation', '0002_auto_20201021_1006'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='ProjectFile',
        ),
    ]
