# Generated by Django 3.1.2 on 2020-10-14 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0002_auto_20201009_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
