# Generated by Django 3.1.2 on 2020-10-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0003_auto_20201021_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='target',
            field=models.TextField(blank=True, null=True),
        ),
    ]
