# Generated by Django 3.1.2 on 2020-10-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0005_auto_20201024_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='seg_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='segment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
