# Generated by Django 3.1.2 on 2020-10-24 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0006_auto_20201024_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='status',
            field=models.CharField(choices=[('NT', 'Not Translated'), ('DR', 'Draft'), ('TR', 'Translated'), ('TJ', 'Translation Rejected'), ('RV', 'Reviewed'), ('RJ', 'Review Rejected'), ('SO', 'Signed Off'), ('SJ', 'Sign-off Rejected')], default='NT', max_length=2),
        ),
        migrations.AlterField(
            model_name='segment',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='translation.projectfile'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='seg_id',
            field=models.IntegerField(),
        ),
    ]
