# Generated by Django 3.1.2 on 2020-11-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0011_auto_20201102_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentenceparser',
            name='exclusion',
            field=models.CharField(default='(?<!Mr\\.)(?<!Mrs\\.)(?<![^\\.\\,]")', max_length=255),
        ),
    ]
