# Generated by Django 3.1.2 on 2020-11-08 12:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('translation', '0012_auto_20201102_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='qaers',
            field=models.ManyToManyField(related_name='qaers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='reviewers',
            field=models.ManyToManyField(related_name='reviewers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='torers',
            field=models.ManyToManyField(related_name='torers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='translators',
            field=models.ManyToManyField(related_name='translators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sentenceparser',
            name='default_regex',
            field=models.CharField(default='(?<=[\\"\'.])(?<![s])\\s+', max_length=255),
        ),
        migrations.AlterField(
            model_name='sentenceparser',
            name='exclusion',
            field=models.CharField(default='(?<!Mr.)(?<!Mrs.)(?<![^.,]")', max_length=255),
        ),
    ]
