# Generated by Django 3.1.2 on 2020-11-09 11:08

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('translation', '0013_auto_20201108_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='qaers',
        ),
        migrations.RemoveField(
            model_name='project',
            name='torers',
        ),
        migrations.AddField(
            model_name='project',
            name='soers',
            field=models.ManyToManyField(related_name='soers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='segment',
            name='review_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='segment',
            name='sign_off_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='segment',
            name='translation_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
