# Generated by Django 3.1.2 on 2020-11-09 11:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0014_auto_20201109_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segment',
            name='review_id',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='sign_off_id',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='translation_id',
        ),
        migrations.AddField(
            model_name='project',
            name='review_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='project',
            name='sign_off_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='project',
            name='translation_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
