# Generated by Django 3.1.2 on 2020-11-16 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0015_auto_20201109_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortDistanceSegment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
                ('html_snippet', models.TextField()),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translation.segment')),
            ],
        ),
    ]
