# Generated by Django 3.1.2 on 2020-11-14 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0016_project_seg_per_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='seg_per_page',
        ),
        migrations.CreateModel(
            name='ProjectPagination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seg_per_page', models.IntegerField(default=50)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pagination', to='translation.project')),
            ],
        ),
    ]
