# Generated by Django 3.1.2 on 2020-11-16 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0016_shortdistancesegment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortdistancesegment',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_distance_seg', to='translation.segment'),
        ),
    ]
