# Generated by Django 3.1.2 on 2020-11-26 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0018_auto_20201118_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('para_num', models.IntegerField()),
                ('default_wrapper', models.CharField(max_length=255)),
                ('projectfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translation.projectfile')),
            ],
        ),
        migrations.AddField(
            model_name='segment',
            name='para_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_file_id', models.IntegerField()),
                ('tag_wrapper', models.CharField(max_length=255)),
                ('paragraph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translation.paragraph')),
            ],
        ),
    ]
