# Generated by Django 3.1.2 on 2020-11-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0019_auto_20201126_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='default_wrapper',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_wrapper',
            field=models.TextField(),
        ),
    ]
