# Generated by Django 3.1.2 on 2020-11-27 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0020_auto_20201126_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='in_file_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_wrapper',
            field=models.TextField(default=0),
        ),
    ]
