# Generated by Django 3.1.2 on 2020-11-27 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0021_auto_20201127_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='projectfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='translation.projectfile'),
        ),
    ]
