# Generated by Django 3.1.2 on 2020-12-02 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0022_auto_20201127_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraph',
            name='hex_place_holder',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='paragraph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='translation.paragraph'),
        ),
    ]
