# Generated by Django 3.1.2 on 2020-12-03 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0023_auto_20201202_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag_wrapper',
            new_name='wrapper',
        ),
        migrations.AlterField(
            model_name='sentenceparser',
            name='default_regex',
            field=models.CharField(default='(?<=[\\"\'.>])(?<![s])\\s+', max_length=255),
        ),
    ]
