# Generated by Django 3.1.2 on 2020-12-03 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0024_auto_20201203_0458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paragraph',
            old_name='hex_place_holder',
            new_name='hex_placeholder',
        ),
    ]
