# Generated by Django 3.1.2 on 2020-12-04 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0025_auto_20201203_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paragraph',
            old_name='default_wrapper',
            new_name='wrapper',
        ),
    ]
