# Generated by Django 3.1.2 on 2020-12-10 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0026_auto_20201204_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='_soup_tag',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
