# Generated by Django 3.1.2 on 2020-12-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0027_tag__soup_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='_soup_tag',
            new_name='_wrapper',
        ),
        migrations.RemoveField(
            model_name='paragraph',
            name='wrapper',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='wrapper',
        ),
        migrations.AddField(
            model_name='paragraph',
            name='_wrapper',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
