# Generated by Django 3.1.2 on 2020-12-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0028_auto_20201210_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='source_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
