# Generated by Django 3.1.2 on 2020-12-23 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0029_tag_source_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='processed_soup',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sentenceparser',
            name='exclusion',
            field=models.CharField(default='(?<!Mr.)(?<!Mrs.)(?<!endtag>)(?<![^.,]")', max_length=255),
        ),
    ]
