# Generated by Django 3.1.2 on 2020-12-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0030_auto_20201223_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='hex_placeholder',
            field=models.CharField(default='adsasdasdasdasd', max_length=32),
            preserve_default=False,
        ),
    ]
