# Generated by Django 3.1.2 on 2020-12-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0031_auto_20201228_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='original_soup',
            field=models.TextField(blank=True, null=True),
        ),
    ]
