# Generated by Django 3.1.2 on 2021-01-12 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0032_projectfile_original_soup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortdistancesegment',
            old_name='html_snippet',
            new_name='source_html_snippet',
        ),
    ]
