# Generated by Django 3.1.2 on 2021-01-12 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0033_auto_20210112_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortdistancesegment',
            name='target_html_snippet',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='shortdistancesegment',
            name='source_html_snippet',
            field=models.TextField(blank=True),
        ),
    ]
